from flask import Blueprint, request, jsonify, send_file
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from io import BytesIO

donate_bp = Blueprint('donate', __name__)

@donate_bp.route('/api/generate-pdf', methods=['POST'])
def generate_pdf():
    """
    Generates a PDF for Project Maasadguru Social Services
    ---
    parameters:
      - name: body
        in: body
        required: false
        schema:
          properties:
            content:
              type: string
              description: Additional custom details for the PDF
    responses:
      200:
        description: Returns a generated PDF file
        content:
          application/pdf:
            schema:
              type: string
              format: binary
      500:
        description: Server error
    """
    try:
        data = request.json or {}
        buffer = BytesIO()
        p = canvas.Canvas(buffer, pagesize=letter)
        width, height = letter

        # Title
        p.setFont("Helvetica-Bold", 24)
        p.drawCentredString(width/2, height - 50, "Project Maasadguru Social Services")
        
        # Subtitle
        p.setFont("Helvetica", 12)
        p.drawCentredString(width/2, height - 70, "Regd. No: 584/2024 | Hyderabad, Telangana")
        
        # Separator Line
        p.line(50, height - 85, width - 50, height - 85)

        # Content
        p.setFont("Helvetica-Bold", 16)
        p.drawString(50, height - 120, "1. Executive Summary")
        p.setFont("Helvetica", 10)
        p.drawString(50, height - 140, "Maasadguru Social Service is dedicated to socio-economic development in remote districts of Telangana.")
        
        p.setFont("Helvetica-Bold", 16)
        p.drawString(50, height - 180, "2. Key Objectives")
        p.setFont("Helvetica", 10)
        objectives = [
            "- Educational Scholarships for rural students",
            "- Medical support and health camps",
            "- Rural development and infrastructure support",
            "- Women empowerment and vocational training"
        ]
        y = height - 200
        for obj in objectives:
            p.drawString(70, y, obj)
            y -= 20

        # Dynamic Content from Request
        if data.get('content'):
            p.setFont("Helvetica-Bold", 16)
            p.drawString(50, y - 20, "3. Custom Project Details")
            p.setFont("Helvetica", 10)
            p.drawString(50, y - 40, data.get('content')[:1000])

        # Footer
        p.setFont("Helvetica-Oblique", 8)
        p.drawCentredString(width/2, 30, "Generated by Maasadguru Backend System | maasadguru@gmail.com")

        p.showPage()
        p.save()

        buffer.seek(0)
        return send_file(
            buffer,
            as_attachment=True,
            download_name="Maasadguru_Project_Overview.pdf",
            mimetype='application/pdf'
        )
    except Exception as e:
        return jsonify({"error": str(e)}), 500
